import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all pages

  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-blue-500 flex items-center justify-between">
          <Link href="/">Tom Charon</Link>
          <div className="flex items-center gap-5">
            {pages.map((page) => (
              <Link href={`/${page.slug}`} key={page._id}>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        {children}
        <div className="bg-blue-500"> This is the footer</div>
      </body>
    </html>
  );
}

export const revalidate = 3;
